baseURL = 'https://kalja.band'
languageCode = 'en-us'
title = 'Kalja'
theme ='hugo-classic'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser.attribute]
      block = true
      title = true


[menus]
[[menus.main]]
  name = "INSTA"
  url = "https://www.instagram.com/kalja.band/"
